import { kv, KEYS } from './index';

/**
 * AIX Readable Memory System (Pattern 3)
 * Transforms complex database state into human-readable, git-backable formats (Markdown + JSONL).
 */
export class ReadableMemory {
  /**
   * Generates a MEMORY.md summary for an agent's long-term facts.
   */
  static async exportToMarkdown(agentId: string): Promise<string> {
    const skills = await kv.smembers<string>(KEYS.memSkill(agentId));
    const memory = await kv.lrange<any>(KEYS.memory(agentId), 0, 50);

    let md = `# Agent Memory: ${agentId}\n\n`;
    
    md += `## 🧠 Learned Skills (Hermes Layer 2)\n`;
    if (skills.length > 0) {
      skills.forEach(s => md += `- ${s}\n`);
    } else {
      md += `*No skills learned yet.*\n`;
    }

    md += `\n## 📜 Recent Interactions (JSONL Pattern)\n`;
    md += `\`\`\`jsonl\n`;
    memory.forEach(m => {
      const entry = typeof m === 'string' ? JSON.parse(m) : m;
      md += `${JSON.stringify(entry)}\n`;
    });
    md += `\`\`\`\n`;

    md += `\n---\n*Generated by AIX Sovereign Protocol at ${new Date().toISOString()}*`;
    return md;
  }

  /**
   * Simulates a "Daily Transcript" in JSONL format.
   */
  static async getDailyJSONL(agentId: string, date: string): Promise<string> {
    // In a real implementation, we'd fetch from a specific date-bucketed key
    const memory = await kv.lrange<any>(KEYS.memory(agentId), 0, -1);
    return memory.map(m => JSON.stringify(m)).join('\n');
  }
}
