/**
 * Type-safe environment variable access
 * Generated by AIX Evolution Loop
 */
import { z } from 'zod';

const EnvSchema = z.object({
  // Authentication
  JWT_SECRET: z.string().min(16),

  // Pi Network
  PI_API_KEY: z.string().min(1),
  PI_APP_ID: z.string().min(1),
  PI_ENV: z.enum(['sandbox', 'production']).default('sandbox'),

  // OpenAI
  OPENAI_API_KEY: z.string().min(1),

  // Upstash Redis
  KV_REST_API_URL: z.string().url(),
  KV_REST_API_TOKEN: z.string().min(1),

  // App
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  APP_URL: z.string().url().default('http://localhost:3000'),
});

const isProd = process.env.NODE_ENV === 'production';

function getRawEnv() {
  return {
    JWT_SECRET: process.env.JWT_SECRET || (isProd ? undefined : 'dev_secret_369_change_me_to_something_long'),
    PI_API_KEY: process.env.PI_API_KEY,
    PI_APP_ID: process.env.PI_APP_ID,
    PI_ENV: process.env.PI_ENVIRONMENT,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    KV_REST_API_URL: process.env.KV_REST_API_URL,
    KV_REST_API_TOKEN: process.env.KV_REST_API_TOKEN,
    NODE_ENV: process.env.NODE_ENV,
    APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  };
}

function validateEnv() {
  const raw = getRawEnv();
  const result = EnvSchema.safeParse(raw);

  if (!result.success) {
    const missing = result.error.issues.map(i => i.path.join('.')).join(', ');
    if (isProd) {
      throw new Error(`CRITICAL: Missing or invalid environment variables: ${missing}`);
    } else {
      console.warn(`[Env] Warning: Missing or invalid environment variables: ${missing}`);
      // In dev, we might want to continue with partial env, but safely
      return raw as unknown as z.infer<typeof EnvSchema>;
    }
  }

  return result.data;
}

export const env = validateEnv();
export type Env = z.infer<typeof EnvSchema>;
