/**
 * Type-safe environment variable access
 * Generated by AIX Evolution Loop
 */
function requireEnv(key: string): string {
  const val = process.env[key];
  if (!val) throw new Error(`Missing required env: ${key}`);
  return val;
}

export const env = {
  // Pi Network
  PI_API_KEY:       process.env.PI_API_KEY || '',
  PI_APP_ID:        process.env.PI_APP_ID || '',
  PI_ENV:           (process.env.PI_ENVIRONMENT || 'sandbox') as 'sandbox' | 'production',

  // OpenAI
  OPENAI_API_KEY:   process.env.OPENAI_API_KEY || '',

  // Upstash Redis
  KV_REST_API_URL:  process.env.KV_REST_API_URL || '',
  KV_REST_API_TOKEN: process.env.KV_REST_API_TOKEN || '',

  // App
  NODE_ENV:         process.env.NODE_ENV || 'development',
  APP_URL:          process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
} as const;

export type Env = typeof env;
