/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema for AIX (Artificial Intelligence eXchange) file format. Created by Mohamed Abdelaziz - AMRIKYY AI Solutions 2026
 */
export interface AIXFormatSchemaV10 {
  /**
   * Agent metadata and identification
   */
  meta: {
    /**
     * AIX format version (semantic versioning)
     */
    version: string;
    /**
     * Unique identifier (UUID v4)
     */
    id: string;
    /**
     * Agent name
     */
    name: string;
    /**
     * Human-readable description
     */
    description?: string;
    /**
     * Creation timestamp (ISO 8601)
     */
    created: string;
    /**
     * Last update timestamp (ISO 8601)
     */
    updated?: string;
    /**
     * Author name or identifier
     */
    author: string;
    /**
     * Classification tags
     *
     * @minItems 0
     * @maxItems 10
     */
    tags?:
      | []
      | [string]
      | [string, string]
      | [string, string, string]
      | [string, string, string, string]
      | [string, string, string, string, string]
      | [string, string, string, string, string, string]
      | [string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string, string, string];
    /**
     * License identifier (SPDX format)
     */
    license?: string;
    /**
     * Agent homepage URL
     */
    homepage?: string;
    /**
     * Source repository URL
     */
    repository?: string;
    /**
     * Documentation URL
     */
    documentation?: string;
    /**
     * Base64-encoded icon or URL
     */
    icon?: string;
    /**
     * Primary language (ISO 639-1)
     */
    language?: string;
    /**
     * Target AI framework
     */
    framework?: string;
    /**
     * Required runtime version
     */
    runtime_version?: string;
    [k: string]: unknown;
  };
  /**
   * Agent personality and behavior
   */
  persona: {
    /**
     * Agent's primary role
     */
    role: string;
    /**
     * Communication style
     */
    tone?: string;
    /**
     * Response style
     */
    style?: string;
    /**
     * Core behavioral instructions
     */
    instructions: string;
    /**
     * Behavioral constraints
     */
    constraints?: string[];
    /**
     * Personality attributes
     */
    personality_traits?: {
      [k: string]: string;
    };
    /**
     * Sample conversations
     */
    example_responses?: {
      question?: string;
      answer?: string;
      [k: string]: unknown;
    }[];
    /**
     * Sampling temperature
     */
    temperature?: number;
    /**
     * Preferred context size
     */
    context_window?: number;
    /**
     * Preferred output format
     */
    response_format?: string;
    [k: string]: unknown;
  };
  /**
   * Agent capabilities
   */
  skills?: {
    /**
     * Skill identifier
     */
    name: string;
    /**
     * Skill description
     */
    description: string;
    /**
     * Whether skill is active
     */
    enabled?: boolean;
    /**
     * Skill-specific parameters
     */
    parameters?: {
      [k: string]: unknown;
    };
    /**
     * Activation triggers
     */
    triggers?: string[];
    /**
     * Usage examples
     */
    examples?: string[];
    /**
     * Execution priority
     */
    priority?: number;
    /**
     * Max execution time (seconds)
     */
    timeout?: number;
    [k: string]: unknown;
  }[];
  /**
   * API integrations
   */
  apis?: {
    /**
     * API identifier
     */
    name: string;
    /**
     * API base URL
     */
    base_url: string;
    /**
     * API purpose
     */
    description?: string;
    /**
     * API version
     */
    version?: string;
    /**
     * Authentication configuration
     */
    auth?: {
      type?: "bearer" | "api_key" | "oauth2" | "basic" | "none";
      location?: "header" | "query" | "body";
      key_name?: string;
      [k: string]: unknown;
    };
    endpoints?: {
      path?: string;
      method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
      description?: string;
      parameters?: {
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }[];
    rate_limit?: {
      requests?: number;
      period?: number;
      [k: string]: unknown;
    };
    timeout?: number;
    retry?: {
      max_attempts?: number;
      backoff?: "exponential" | "linear" | "constant";
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  /**
   * Model Context Protocol configuration
   */
  mcp?: {
    servers?: {
      /**
       * Server identifier
       */
      name: string;
      /**
       * Executable command
       */
      command: string;
      /**
       * Command arguments
       */
      args?: string[];
      /**
       * Environment variables
       */
      env?: {
        [k: string]: string;
      };
      description?: string;
      capabilities?: string[];
      timeout?: number;
      auto_start?: boolean;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * Memory system configuration
   */
  memory?: {
    /**
     * Conversation history
     */
    episodic?: {
      enabled?: boolean;
      max_messages?: number;
      retention_days?: number;
      storage?: "local" | "cloud" | "vector_db" | "database";
      [k: string]: unknown;
    };
    /**
     * Knowledge graphs
     */
    semantic?: {
      enabled?: boolean;
      embedding_model?: string;
      vector_db?: string;
      similarity_threshold?: number;
      max_results?: number;
      [k: string]: unknown;
    };
    /**
     * Workflows and processes
     */
    procedural?: {
      enabled?: boolean;
      storage?: string;
      max_workflows?: number;
      [k: string]: unknown;
    };
    persistence?: {
      enabled?: boolean;
      backend?: "file" | "database" | "redis" | "s3" | "postgresql" | "sqlite";
      config?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Agent resource requirements for deployment and execution
   */
  requirements?: {
    /**
     * Vision-Language-Action payload requirements
     */
    vla?: {
      /**
       * Identifies which VLA runtime adapter should process this payload.
       */
      adapter: "openpi" | "π0.7" | "generic";
      /**
       * Visual perception inputs.
       */
      vision?: {
        [k: string]: unknown;
      };
      /**
       * Natural language instruction or context.
       */
      language?: {
        [k: string]: unknown;
      };
      /**
       * Motor or decision action outputs.
       */
      action?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Security and integrity data
   */
  security: {
    checksum: {
      algorithm: "sha256" | "sha512" | "blake3";
      /**
       * Hex-encoded hash value
       */
      value: string;
      /**
       * What is included in checksum
       */
      scope?: string;
      [k: string]: unknown;
    };
    /**
     * Digital signature
     */
    signature?: {
      algorithm?: "RSA-SHA256" | "Ed25519" | "ECDSA-SHA256";
      /**
       * Base64-encoded signature
       */
      value?: string;
      /**
       * PEM-encoded public key
       */
      public_key?: string;
      /**
       * Signer identifier
       */
      signer?: string;
      /**
       * Signing timestamp (ISO 8601)
       */
      timestamp?: string;
      [k: string]: unknown;
    };
    /**
     * Encryption metadata
     */
    encryption?: {
      encrypted?: boolean;
      algorithm?: "AES-256-GCM" | "ChaCha20-Poly1305" | "none";
      key_fingerprint?: string;
      [k: string]: unknown;
    };
    /**
     * Capability restrictions
     */
    capabilities?: {
      allowed_operations?: string[];
      restricted_operations?: string[];
      restricted_domains?: string[];
      max_api_calls_per_minute?: number;
      max_memory_mb?: number;
      sandbox?: boolean;
      [k: string]: unknown;
    };
    /**
     * Compliance and audit
     */
    compliance?: {
      standards?: string[];
      certifications?: string[];
      audit_log?: boolean;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * AxiomID Identity block. axiomid.app is the Root Authority for all issued identities.
   */
  identity_layer?: {
    /**
     * Unique Axiom identifier enforcing did:axiom:axiomid.app:<id> format.
     */
    id: string;
    /**
     * Root authority domain. Must resolve to axiomid.app.
     */
    authority: "axiomid.app";
    /**
     * ISO 8601 timestamp of identity issuance.
     */
    issuedAt: string;
    /**
     * Optional expiry timestamp for ephemeral identities.
     */
    expiresAt?: string;
    /**
     * Public key material for cryptographic verification.
     */
    publicKey?: {
      /**
       * Cryptographic algorithm used to generate the key pair.
       */
      algorithm: "Ed25519" | "secp256k1";
      /**
       * Base64url-encoded public key bytes.
       */
      value: string;
      encoding?: "base64url" | "hex";
      [k: string]: unknown;
    };
    /**
     * Cryptographic signature over the canonical payload hash.
     */
    signature?: {
      /**
       * Algorithm used to produce the signature.
       */
      algorithm: "Ed25519" | "secp256k1";
      /**
       * Base64url-encoded signature bytes.
       */
      value: string;
      /**
       * JSON canonicalization scheme used before signing.
       */
      canonicalization?: "JCS" | "RFC8785";
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
