/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enhanced JSON Schema for AIX (Artificial Intelligence eXchange) v1.3 - Sovereign Protocol. Created by Mohamed Abdelaziz - AMRIKYY AI Solutions 2026
 */
export interface EnhancedAIXFormatSchema {
  /**
   * Pi Network specific configuration and SDK integration
   */
  pi_network?: {
    /**
     * Pi App identifier from Pi Dev Studio
     */
    app_id: string;
    /**
     * Pi Network execution environment
     */
    environment: "sandbox" | "production";
    /**
     * Required Pi SDK version
     */
    sdk_version?: string;
    /**
     * Pi payment provider identifier
     */
    payment_provider?: string;
    /**
     * Whether the agent requires KYCed Pi users
     */
    kyc_required?: boolean;
    [k: string]: unknown;
  };
  /**
   * Agent metadata and identification
   */
  meta: {
    /**
     * Agent version (semantic versioning)
     */
    version: string;
    /**
     * AIX format version
     */
    format_version?: "1.0" | "1.2" | "1.3";
    /**
     * Unique identifier (UUID v4)
     */
    id: string;
    /**
     * Agent name
     */
    name: string;
    /**
     * Human-readable description
     */
    description?: string;
    /**
     * Creation timestamp (ISO 8601)
     */
    created: string;
    /**
     * Last update timestamp (ISO 8601)
     */
    updated?: string;
    /**
     * Author name or identifier
     */
    author: string;
    /**
     * Classification tags
     *
     * @minItems 0
     * @maxItems 10
     */
    tags?:
      | []
      | [string]
      | [string, string]
      | [string, string, string]
      | [string, string, string, string]
      | [string, string, string, string, string]
      | [string, string, string, string, string, string]
      | [string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string, string, string];
    /**
     * License identifier (SPDX format)
     */
    license?: string;
    /**
     * Agent homepage URL
     */
    homepage?: string;
    /**
     * Source repository URL
     */
    repository?: string;
    /**
     * Documentation URL
     */
    documentation?: string;
    /**
     * Base64-encoded icon or URL
     */
    icon?: string;
    /**
     * Primary language (ISO 639-1)
     */
    language?: string;
    /**
     * Target AI framework
     */
    framework?: string;
    /**
     * Required runtime version
     */
    runtime_version?: string;
    /**
     * Agent Genealogy and heritage tracking (Agent Lineage)
     */
    lineage?: {
      /**
       * DID or ID of the parent agent
       */
      parent_id?: string;
      relationship?: "fork" | "clone" | "ancestor" | "template";
      timestamp?: string;
      /**
       * Cryptographic proof of lineage
       */
      signature?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * Agent personality and behavior
   */
  persona: {
    /**
     * Agent's primary role
     */
    role: string;
    /**
     * Communication style
     */
    tone?: string;
    /**
     * Response style
     */
    style?: string;
    /**
     * Core behavioral instructions
     */
    instructions: string;
    /**
     * Behavioral constraints
     */
    constraints?: string[];
    /**
     * Personality attributes
     */
    personality_traits?: {
      [k: string]: string;
    };
    /**
     * Sample conversations
     */
    example_responses?: {
      question?: string;
      answer?: string;
      [k: string]: unknown;
    }[];
    /**
     * Sampling temperature
     */
    temperature?: number;
    /**
     * Preferred context size
     */
    context_window?: number;
    /**
     * Preferred output format
     */
    response_format?: string;
    [k: string]: unknown;
  };
  /**
   * Agent capabilities
   */
  skills?: {
    /**
     * Skill identifier
     */
    name: string;
    /**
     * Skill description
     */
    description: string;
    /**
     * Whether skill is active
     */
    enabled?: boolean;
    /**
     * Skill-specific parameters
     */
    parameters?: {
      [k: string]: unknown;
    };
    /**
     * Activation triggers
     */
    triggers?: string[];
    /**
     * Usage examples
     */
    examples?: string[];
    /**
     * Execution priority
     */
    priority?: number;
    /**
     * Max execution time (seconds)
     */
    timeout?: number;
    [k: string]: unknown;
  }[];
  /**
   * API integrations
   */
  apis?: {
    /**
     * API identifier
     */
    name: string;
    /**
     * API base URL
     */
    base_url: string;
    /**
     * API purpose
     */
    description?: string;
    /**
     * API version
     */
    version?: string;
    /**
     * Authentication configuration
     */
    auth?: {
      type?: "bearer" | "api_key" | "oauth2" | "basic" | "none";
      location?: "header" | "query" | "body";
      key_name?: string;
      [k: string]: unknown;
    };
    endpoints?: {
      path?: string;
      method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
      description?: string;
      parameters?: {
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }[];
    rate_limit?: {
      requests?: number;
      period?: number;
      [k: string]: unknown;
    };
    timeout?: number;
    retry?: {
      max_attempts?: number;
      backoff?: "exponential" | "linear" | "constant";
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  /**
   * Agentic capabilities and features
   */
  capabilities?: {
    streaming?: boolean;
    push_notifications?: boolean;
    state_history?: boolean;
    voice_interaction?: boolean;
    [k: string]: unknown;
  };
  /**
   * Model Context Protocol configuration
   */
  mcp?: {
    servers?: {
      /**
       * Server identifier
       */
      name: string;
      /**
       * Executable command
       */
      command: string;
      /**
       * Command arguments
       */
      args?: string[];
      /**
       * Environment variables
       */
      env?: {
        [k: string]: string;
      };
      description?: string;
      capabilities?: string[];
      timeout?: number;
      auto_start?: boolean;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * Memory system configuration
   */
  memory?: {
    /**
     * Conversation history
     */
    episodic?: {
      enabled?: boolean;
      max_messages?: number;
      retention_days?: number;
      storage?: "local" | "cloud" | "vector_db" | "database";
      [k: string]: unknown;
    };
    /**
     * Knowledge graphs
     */
    semantic?: {
      enabled?: boolean;
      embedding_model?: string;
      vector_db?: string;
      similarity_threshold?: number;
      max_results?: number;
      [k: string]: unknown;
    };
    /**
     * Workflows and processes
     */
    procedural?: {
      enabled?: boolean;
      storage?: string;
      max_workflows?: number;
      [k: string]: unknown;
    };
    persistence?: {
      enabled?: boolean;
      backend?: "file" | "database" | "redis" | "s3" | "postgresql" | "sqlite";
      config?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Agent resource requirements for deployment and execution
   */
  requirements?: {
    /**
     * Hardware requirements
     */
    hardware?: {
      /**
       * Minimum CPU cores required
       */
      cpu_cores?: number;
      /**
       * Minimum RAM in MB
       */
      memory_mb?: number;
      /**
       * Minimum storage in MB
       */
      storage_mb?: number;
      /**
       * Whether GPU is required
       */
      gpu_required?: boolean;
      /**
       * Minimum GPU memory in MB (if GPU required)
       */
      gpu_memory_mb?: number;
      [k: string]: unknown;
    };
    /**
     * Software dependencies
     */
    software?: {
      /**
       * Required runtime environment
       */
      runtime?: string;
      /**
       * Required software dependencies
       */
      dependencies?: string[];
      /**
       * Required Python version (if applicable)
       */
      python_version?: string;
      /**
       * Required Node.js version (if applicable)
       */
      node_version?: string;
      [k: string]: unknown;
    };
    /**
     * Network requirements
     */
    network?: {
      /**
       * Whether internet access is required
       */
      internet_access?: boolean;
      /**
       * Minimum bandwidth in Mbps
       */
      bandwidth_mbps?: number;
      /**
       * Domains that the agent needs to access
       */
      allowed_domains?: string[];
      [k: string]: unknown;
    };
    /**
     * Vision-Language-Action payload requirements
     */
    vla?: {
      /**
       * Identifies which VLA runtime adapter should process this payload.
       */
      adapter: "openpi" | "π0.7" | "generic";
      /**
       * Visual perception inputs.
       */
      vision?: {
        [k: string]: unknown;
      };
      /**
       * Natural language instruction or context.
       */
      language?: {
        [k: string]: unknown;
      };
      /**
       * Motor or decision action outputs.
       */
      action?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Agent Bill of Materials (ABOM) - AI-SBOM (CycloneDX 1.6 compatible) for supply chain transparency
   */
  abom?: {
    /**
     * SHA-256 hash of the ABOM constituents/dependencies for integrity verification
     */
    integrity_hash?: string;
    /**
     * Base models and architectures utilized by the agent
     */
    models?: {
      name: string;
      version: string;
      /**
       * e.g. 70B, 8B
       */
      parameters?: string;
      weights_hash?: string;
      [k: string]: unknown;
    }[];
    /**
     * Training or fine-tuning datasets used
     */
    datasets?: {
      name?: string;
      provenance?: string;
      sensitivity?: "public" | "proprietary" | "sensitive";
      [k: string]: unknown;
    }[];
    /**
     * Software components and dependencies
     */
    constituents?: {
      name: string;
      version: string;
      hash?: string;
      license?: string;
      [k: string]: unknown;
    }[];
    governance?: {
      ethical_constraints?: string[];
      compliance_attestations?: string[];
      [k: string]: unknown;
    };
    environmental_impact?: {
      training_energy_kwh?: number;
      carbon_offset?: boolean;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Economic and transaction layer for agent settlements and payments
   */
  economics?: {
    /**
     * Pi Network Smart Contract interface for automated settlements
     */
    pi_smart_contract?: {
      /**
       * Contract address on the Pi Network
       */
      address: string;
      network: "mainnet" | "testnet" | "sandbox";
      escrow_enabled?: boolean;
      abi_url?: string;
      [k: string]: unknown;
    };
    /**
     * Pricing model for agent usage (Legacy Pricing included in Economics Layer)
     */
    pricing?: {
      /**
       * Pricing model type
       */
      model?: "pay_per_call" | "subscription" | "freemium" | "tiered";
      /**
       * Cost per API call
       */
      cost_per_call?: {
        /**
         * Cost amount
         */
        amount?: number;
        /**
         * Currency code (ISO 4217)
         */
        currency?: string;
        [k: string]: unknown;
      };
      /**
       * Subscription pricing
       */
      subscription?: {
        monthly_fee?: {
          amount?: number;
          currency?: string;
          [k: string]: unknown;
        };
        /**
         * Number of calls included in subscription
         */
        included_calls?: number;
        additional_call_cost?: {
          amount?: number;
          currency?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * Tiered pricing based on usage
       */
      tiered_pricing?: {
        min_calls?: number;
        max_calls?: number;
        cost_per_call?: {
          amount?: number;
          currency?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Security and integrity data
   */
  security: {
    /**
     * Supported authentication schemes
     */
    authentication?: {
      scheme?: string;
      description?: string;
      [k: string]: unknown;
    }[];
    checksum: {
      algorithm: "sha256" | "sha512" | "blake3";
      /**
       * Hex-encoded hash value
       */
      value: string;
      /**
       * What is included in checksum
       */
      scope?: string;
      [k: string]: unknown;
    };
    /**
     * Digital signature
     */
    signature?: {
      algorithm?: "RSA-SHA256" | "Ed25519" | "ECDSA-SHA256";
      /**
       * Base64-encoded signature
       */
      value?: string;
      /**
       * PEM-encoded public key
       */
      public_key?: string;
      /**
       * Signer identifier
       */
      signer?: string;
      /**
       * Signing timestamp (ISO 8601)
       */
      timestamp?: string;
      [k: string]: unknown;
    };
    /**
     * Encryption metadata
     */
    encryption?: {
      encrypted?: boolean;
      algorithm?: "AES-256-GCM" | "ChaCha20-Poly1305" | "none";
      key_fingerprint?: string;
      [k: string]: unknown;
    };
    /**
     * Capability restrictions
     */
    capabilities?: {
      allowed_operations?: string[];
      restricted_operations?: string[];
      restricted_domains?: string[];
      max_api_calls_per_minute?: number;
      max_memory_mb?: number;
      sandbox?: boolean;
      [k: string]: unknown;
    };
    /**
     * Compliance and audit
     */
    compliance?: {
      standards?: string[];
      certifications?: string[];
      audit_log?: boolean;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * AxiomID Identity block. axiomid.app is the Root Authority for all issued identities.
   */
  identity_layer: {
    /**
     * Unique Axiom identifier enforcing did:axiom or did:axiom:axiomid.app format.
     */
    id: string;
    /**
     * Pi Network KYC tier (0: None, 1: Basic, 2: Full, 3: Sovereign)
     */
    kyc_tier?: number;
    /**
     * Whether the identity has been verified by the authority
     */
    verified?: boolean;
    /**
     * Root authority domain. Must resolve to axiomid.app.
     */
    authority: "axiomid.app";
    /**
     * ISO 8601 timestamp of identity issuance.
     */
    issuedAt: string;
    /**
     * Optional expiry timestamp for ephemeral identities.
     */
    expiresAt?: string;
    /**
     * Public key material for cryptographic verification.
     */
    publicKey?: {
      /**
       * Cryptographic algorithm used to generate the key pair.
       */
      algorithm: "Ed25519" | "secp256k1";
      /**
       * Base64url-encoded public key bytes.
       */
      value: string;
      encoding?: "base64url" | "hex";
      [k: string]: unknown;
    };
    /**
     * Cryptographic signature over the canonical payload hash.
     */
    signature?: {
      /**
       * Algorithm used to produce the signature.
       */
      algorithm: "Ed25519" | "secp256k1";
      /**
       * Base64url-encoded signature bytes.
       */
      value: string;
      /**
       * JSON canonicalization scheme used before signing.
       */
      canonicalization?: "JCS" | "RFC8785";
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Live Voice Models integration for human-like conversational experiences.
   */
  live_voice?: {
    enabled: boolean;
    /**
     * The live voice model provider.
     */
    provider: "openai-realtime" | "hume" | "elevenlabs" | "generic";
    /**
     * The specific voice profile or identifier to use.
     */
    voice_id?: string;
    latency_mode?: "ultra_low" | "standard" | "high_quality";
    [k: string]: unknown;
  };
  /**
   * Black Box logs and ABOM query server for AIX agents
   */
  black_box?: {
    /**
     * Whether the black box logging is enabled
     */
    enabled?: boolean;
    /**
     * Cryptographically signed trace logs for the regulator package
     */
    traces?: {
      timestamp: string;
      /**
       * The action or tool that was executed
       */
      action: string;
      /**
       * Details about the execution, parameters, output or memory state
       */
      details?: {
        [k: string]: unknown;
      };
      signature: {
        algorithm: string;
        /**
         * Base64 encoded Ed25519 signature of the log entry
         */
        value: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
