// AUTO-GENERATED — placeholder. Real content will be generated by `npm run generate:types:unified`.
// This file is committed to make the types/ directory visible and to document the main AIXDocument shape.

export interface AIXDocument {
  meta: Meta;
  persona: Persona;
  security: Security;
  identity_layer: IdentityLayer;
  skills?: Skill[];
  apis?: API[];
  mcp?: MCP;
  memory?: Memory;
  economics?: Economics;
  abom?: ABOM;
  pi_network?: PiNetwork;
}

export interface Meta {
  version: string;
  id: string;
  name: string;
  description?: string;
  created: string;
  updated?: string;
  author: string;
}

export interface Persona {
  role: string;
  instructions: string;
}

export interface Security {
  checksum: {
    algorithm: 'sha256' | 'sha512' | 'blake3';
    value: string;
  };
}

export interface IdentityLayer {
  id: string;
  authority: string;
  issuedAt: string;
  expiresAt?: string;
}

export interface Skill {
  name: string;
  description: string;
}

export interface API {
  name: string;
  base_url: string;
}

export interface MCP {
  servers: MCPServer[];
}

export interface MCPServer {
  name: string;
  command: string;
}

export interface Memory {
  episodic?: { enabled?: boolean };
  semantic?: { enabled?: boolean; similarity_threshold?: number };
  procedural?: { enabled?: boolean };
}

export interface Economics {
  // Filled by generator from schema
}

export interface ABOM {
  // Filled by generator from schema
}

export interface PiNetwork {
  app_id: string;
  environment: 'sandbox' | 'production';
}
