/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Official JSON Schema for Axiom AIX (Artificial Intelligence eXchange) file format with identity and economics layers. The Digital DNA of autonomous AI agents.
 */
export interface AxiomAIXStandardSchema {
  /**
   * AIX format version (semantic versioning)
   */
  version: string;
  /**
   * Agent metadata and identification
   */
  metadata: {
    /**
     * Agent name
     */
    name: string;
    /**
     * Unique identifier (UUID v4)
     */
    id: string;
    /**
     * Creation timestamp (ISO 8601)
     */
    created_at: string;
    /**
     * Author name or identifier
     */
    author: string;
    /**
     * Human-readable description
     */
    description?: string;
    /**
     * Last update timestamp (ISO 8601)
     */
    updated_at?: string;
    /**
     * Classification tags
     *
     * @minItems 0
     * @maxItems 10
     */
    tags?:
      | []
      | [string]
      | [string, string]
      | [string, string, string]
      | [string, string, string, string]
      | [string, string, string, string, string]
      | [string, string, string, string, string, string]
      | [string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string, string, string];
    /**
     * License identifier (SPDX format)
     */
    license?: string;
    /**
     * Agent homepage URL
     */
    homepage?: string;
    /**
     * Source repository URL
     */
    repository?: string;
    /**
     * Documentation URL
     */
    documentation?: string;
    /**
     * Avatar image URL (supports IPFS)
     */
    avatar_url?: string;
    /**
     * Primary language (ISO 639-1)
     */
    language?: string;
    [k: string]: unknown;
  };
  /**
   * Agent personality and behavior
   */
  persona: {
    /**
     * Agent's primary role
     */
    role: string;
    /**
     * Detailed agent description
     */
    description: string;
    /**
     * Communication style
     */
    tone: string;
    /**
     * Response style
     */
    style?: string;
    /**
     * Behavioral constraints
     */
    constraints?: string[];
    /**
     * Personality attributes
     */
    personality_traits?: {
      [k: string]: string;
    };
    /**
     * Sample conversations
     */
    example_responses?: {
      question?: string;
      answer?: string;
      [k: string]: unknown;
    }[];
    /**
     * Sampling temperature
     */
    temperature?: number;
    /**
     * Preferred context size
     */
    context_window?: number;
    /**
     * Preferred output format
     */
    response_format?: string;
    /**
     * Avatar image URL (supports IPFS)
     */
    avatar_url?: string;
    [k: string]: unknown;
  };
  /**
   * AxiomID Identity block. axiomid.app is the Root Authority for all issued identities.
   */
  identity_layer: {
    /**
     * Unique Axiom identifier enforcing did:axiom:axiomid.app:<id> format.
     */
    id: string;
    /**
     * Root authority domain. Must resolve to axiomid.app.
     */
    authority: "axiomid.app";
    /**
     * ISO 8601 timestamp of identity issuance.
     */
    issuedAt: string;
    /**
     * Optional expiry timestamp for ephemeral identities.
     */
    expiresAt?: string;
    /**
     * Public key material for cryptographic verification.
     */
    publicKey?: {
      /**
       * Cryptographic algorithm used to generate the key pair.
       */
      algorithm: "Ed25519" | "secp256k1";
      /**
       * Base64url-encoded public key bytes.
       */
      value: string;
      encoding?: "base64url" | "hex";
      [k: string]: unknown;
    };
    /**
     * Cryptographic signature over the canonical payload hash.
     */
    signature?: {
      /**
       * Algorithm used to produce the signature.
       */
      algorithm: "Ed25519" | "secp256k1";
      /**
       * Base64url-encoded signature bytes.
       */
      value: string;
      /**
       * JSON canonicalization scheme used before signing.
       */
      canonicalization?: "JCS" | "RFC8785";
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Agent economic model and pricing
   */
  economics: {
    /**
     * Token used for transactions
     */
    token: "AXIOM" | "SOL" | "ETH" | "USDC" | "USDT";
    /**
     * Cost per task in token units
     */
    cost_per_task: number;
    /**
     * Minimum reputation score required to interact with this agent
     */
    min_reputation_required?: number;
    /**
     * Subscription-based pricing model
     */
    subscription_model?: {
      monthly_fee?: number;
      included_tasks?: number;
      additional_task_cost?: number;
      [k: string]: unknown;
    };
    /**
     * Tiered pricing based on usage volume
     */
    tiered_pricing?: {
      min_tasks?: number;
      max_tasks?: number;
      cost_per_task?: number;
      [k: string]: unknown;
    }[];
    /**
     * Revenue sharing model
     */
    revenue_sharing?: {
      percentage?: number;
      /**
       * Wallet address of revenue recipient
       */
      recipient?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Agent capabilities and skills
   */
  superpowers: {
    /**
     * Superpower identifier
     */
    name: string;
    /**
     * Superpower version (semver)
     */
    version: string;
    /**
     * Superpower type
     */
    type: "python_module" | "llm_chain" | "api_integration" | "mcp_server" | "custom";
    /**
     * Superpower description
     */
    description?: string;
    /**
     * Whether superpower is active
     */
    enabled?: boolean;
    /**
     * LLM model name (for llm_chain type)
     */
    model?: string;
    /**
     * Required permissions
     */
    permissions?: ("internet_access" | "file_system" | "camera" | "microphone" | "location")[];
    /**
     * Superpower-specific parameters
     */
    parameters?: {
      [k: string]: unknown;
    };
    /**
     * Activation triggers
     */
    triggers?: string[];
    /**
     * Usage examples
     */
    examples?: string[];
    /**
     * Execution priority
     */
    priority?: number;
    /**
     * Max execution time (seconds)
     */
    timeout?: number;
    [k: string]: unknown;
  }[];
  /**
   * Agent resource requirements for deployment and execution
   */
  requirements?: {
    /**
     * Vision-Language-Action payload requirements
     */
    vla?: {
      /**
       * Identifies which VLA runtime adapter should process this payload.
       */
      adapter: "openpi" | "pi0.7" | "generic";
      /**
       * Visual perception inputs.
       */
      vision?: {
        [k: string]: unknown;
      };
      /**
       * Natural language instruction or context.
       */
      language?: {
        [k: string]: unknown;
      };
      /**
       * Motor or decision action outputs.
       */
      action?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    /**
     * Hardware requirements
     */
    hardware?: {
      /**
       * Minimum CPU cores required
       */
      cpu_cores?: number;
      /**
       * Minimum RAM in MB
       */
      memory_mb?: number;
      /**
       * Minimum storage in MB
       */
      storage_mb?: number;
      /**
       * Whether GPU is required
       */
      gpu_required?: boolean;
      /**
       * Minimum GPU memory in MB (if GPU required)
       */
      gpu_memory_mb?: number;
      [k: string]: unknown;
    };
    /**
     * Software dependencies
     */
    software?: {
      /**
       * Required runtime environment
       */
      runtime?: string;
      /**
       * Required software dependencies
       */
      dependencies?: string[];
      /**
       * Required Python version (if applicable)
       */
      python_version?: string;
      /**
       * Required Node.js version (if applicable)
       */
      node_version?: string;
      [k: string]: unknown;
    };
    /**
     * Network requirements
     */
    network?: {
      /**
       * Whether internet access is required
       */
      internet_access?: boolean;
      /**
       * Minimum bandwidth in Mbps
       */
      bandwidth_mbps?: number;
      /**
       * Domains that the agent needs to access
       */
      allowed_domains?: string[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Security and integrity data
   */
  security?: {
    checksum: {
      algorithm: "sha256" | "sha512" | "blake3";
      /**
       * Hex-encoded hash value
       */
      value: string;
      /**
       * What is included in checksum
       */
      scope?: string;
      [k: string]: unknown;
    };
    /**
     * Digital signature
     */
    signature?: {
      algorithm?: "RSA-SHA256" | "Ed25519" | "ECDSA-SHA256";
      /**
       * Base64-encoded signature
       */
      value?: string;
      /**
       * PEM-encoded public key
       */
      public_key?: string;
      /**
       * Signer identifier
       */
      signer?: string;
      /**
       * Signing timestamp (ISO 8601)
       */
      timestamp?: string;
      [k: string]: unknown;
    };
    /**
     * Encryption metadata
     */
    encryption?: {
      encrypted?: boolean;
      algorithm?: "AES-256-GCM" | "ChaCha20-Poly1305" | "none";
      key_fingerprint?: string;
      [k: string]: unknown;
    };
    /**
     * Capability restrictions
     */
    capabilities?: {
      allowed_operations?: string[];
      restricted_operations?: string[];
      restricted_domains?: string[];
      max_api_calls_per_minute?: number;
      max_memory_mb?: number;
      sandbox?: boolean;
      [k: string]: unknown;
    };
    /**
     * Compliance and audit
     */
    compliance?: {
      standards?: string[];
      certifications?: string[];
      audit_log?: boolean;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
