/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validation schema for manifest.json files, enforcing SHA-256 integrity and digital signatures under the Sovereign Protocol.
 */
export interface AIXManifestValidationSchema {
  /**
   * Manifest format version.
   */
  version: string;
  /**
   * Mapping of filenames to their SHA-256 checksums.
   */
  checksums: {
    /**
     * SHA-256 hex hash.
     */
    [k: string]: string;
  };
  /**
   * Digital signature for the manifest content.
   */
  signature: {
    /**
     * Cryptographic algorithm.
     */
    algorithm: "Ed25519" | "secp256k1";
    /**
     * Base64url encoded signature.
     */
    value: string;
    /**
     * Base64url encoded public key (optional if resolvable via DID).
     */
    publicKey?: string;
    /**
     * Signer identifier (AxiomID / DID).
     */
    signer?: string;
    [k: string]: unknown;
  };
}
