/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Semantic versioning string (e.g. 1.0.0, 1.2.0-beta.1)
 *
 * This interface was referenced by `AIXFormat`'s JSON-Schema
 * via the `definition` "SemVer".
 */
export type SemVer = string;
/**
 * ISO 8601 date-time string
 *
 * This interface was referenced by `AIXFormat`'s JSON-Schema
 * via the `definition` "ISODateTime".
 */
export type ISODateTime = string;
/**
 * UUID v4 identifier
 *
 * This interface was referenced by `AIXFormat`'s JSON-Schema
 * via the `definition` "UUIDv4".
 */
export type UUIDv4 = string;
/**
 * Axiom Decentralized Identifier — did:axiom:axiomid.app:<id>
 *
 * This interface was referenced by `AIXFormat`'s JSON-Schema
 * via the `definition` "AxiomDID".
 */
export type AxiomDID = string;

/**
 * Unified JSON Schema for AIX (Artificial Intelligence eXchange) v1.3 — Sovereign Protocol. The Digital DNA of autonomous AI agents. Created by Mohamed Abdelaziz - AMRIKYY AI Solutions 2026
 */
export interface AIXFormat {
  /**
   * Agent metadata and identification
   */
  meta: {
    version: SemVer;
    /**
     * Unique identifier — UUID v4 or AxiomDID
     */
    id: string;
    name: string;
    description?: string;
    created: ISODateTime;
    updated?: ISODateTime;
    author: string;
    /**
     * @maxItems 10
     */
    tags?:
      | []
      | [string]
      | [string, string]
      | [string, string, string]
      | [string, string, string, string]
      | [string, string, string, string, string]
      | [string, string, string, string, string, string]
      | [string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string, string]
      | [string, string, string, string, string, string, string, string, string, string];
    license?: string;
    homepage?: string;
    repository?: string;
    documentation?: string;
    /**
     * Base64-encoded icon or URL
     */
    icon?: string;
    language?: string;
    framework?: string;
    runtime_version?: string;
    /**
     * AIX format version (e.g. 1.3)
     */
    format_version?: string;
    /**
     * Agent genealogy and heritage tracking
     */
    lineage?: {
      /**
       * DID or UUID of the parent agent
       */
      parent_id: string;
      relationship?: "fork" | "clone" | "ancestor" | "template";
      timestamp?: ISODateTime;
      /**
       * Cryptographic proof of lineage
       */
      signature?: string;
    }[];
    [k: string]: unknown | undefined;
  };
  /**
   * Agent personality and behavior
   */
  persona: {
    role: string;
    /**
     * Display name for the persona
     */
    name?: string;
    tone?: string;
    style?: string;
    instructions: string;
    constraints?: string[];
    personality_traits?: {
      [k: string]: string | undefined;
    };
    example_responses?: {
      question?: string;
      answer?: string;
    }[];
    temperature?: number;
    context_window?: number;
    response_format?: string;
    [k: string]: unknown | undefined;
  };
  /**
   * Security and integrity data
   */
  security: {
    checksum: {
      algorithm: "sha256" | "sha512" | "blake3";
      value: string;
      scope?: string;
    };
    signature?: {
      algorithm?: "RSA-SHA256" | "Ed25519" | "ECDSA-SHA256";
      value?: string;
      public_key?: string;
      signer?: string;
      timestamp?: ISODateTime;
    };
    encryption?: {
      encrypted?: boolean;
      algorithm?: "AES-256-GCM" | "ChaCha20-Poly1305" | "none";
      key_fingerprint?: string;
    };
    capabilities?: {
      allowed_operations?: string[];
      restricted_operations?: string[];
      restricted_domains?: string[];
      max_api_calls_per_minute?: number;
      max_memory_mb?: number;
      sandbox?: boolean;
    };
    compliance?: {
      standards?: string[];
      certifications?: string[];
      audit_log?: boolean;
    };
    /**
     * Shorthand security level label
     */
    level?: string;
    authentication?: string[];
    [k: string]: unknown | undefined;
  };
  /**
   * AxiomID Identity block. axiomid.app is the Root Authority for all issued identities.
   */
  identity_layer: {
    /**
     * Agent DID — AxiomDID or aix: DID
     */
    id: string;
    /**
     * Pi Network KYC tier (0: None, 1: Basic, 2: Full, 3: Sovereign) or label
     */
    kyc_tier?: number | string;
    /**
     * Whether the identity has been verified by the authority
     */
    verified?: boolean;
    /**
     * Root authority domain. Must resolve to axiomid.app.
     */
    authority: "axiomid.app";
    issuedAt: ISODateTime;
    expiresAt?: ISODateTime;
    publicKey?: PublicKey;
    signature?: Signature;
  };
  /**
   * Agent capabilities
   */
  skills?: {
    name: string;
    description: string;
    enabled?: boolean;
    parameters?: {
      [k: string]: unknown | undefined;
    };
    triggers?: string[];
    examples?: string[];
    priority?: number;
    timeout?: number;
  }[];
  /**
   * API integrations
   */
  apis?: {
    name: string;
    base_url: string;
    description?: string;
    version?: string;
    auth?: {
      type?: "bearer" | "api_key" | "oauth2" | "basic" | "none";
      location?: "header" | "query" | "body";
      key_name?: string;
    };
    endpoints?: {
      path?: string;
      method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
      description?: string;
      parameters?: {
        [k: string]: unknown | undefined;
      }[];
    }[];
    rate_limit?: {
      requests?: number;
      period?: number;
    };
    timeout?: number;
    retry?: {
      max_attempts?: number;
      backoff?: "exponential" | "linear" | "constant";
    };
  }[];
  /**
   * Model Context Protocol configuration
   */
  mcp?: {
    servers?: {
      name: string;
      command: string;
      args?: string[];
      env?: {
        [k: string]: string | undefined;
      };
      description?: string;
      capabilities?: string[];
      timeout?: number;
      auto_start?: boolean;
    }[];
    /**
     * MCP discovery prompts (AIX v1.3)
     */
    prompts?: {
      name: string;
      description?: string;
    }[];
  };
  /**
   * Memory system configuration
   */
  memory?: {
    episodic?: {
      enabled?: boolean;
      max_messages?: number;
      retention_days?: number;
      storage?: "local" | "cloud" | "vector_db" | "database";
    };
    semantic?: {
      enabled?: boolean;
      embedding_model?: string;
      vector_db?: string;
      similarity_threshold?: number;
      max_results?: number;
    };
    procedural?: {
      enabled?: boolean;
      storage?: string;
      max_workflows?: number;
    };
    persistence?: {
      enabled?: boolean;
      backend?: "file" | "database" | "redis" | "s3" | "postgresql" | "sqlite";
      config?: {
        [k: string]: unknown | undefined;
      };
    };
  };
  /**
   * Economic and transaction layer for agent settlements and payments
   */
  economics?: {
    /**
     * Shorthand pricing model field
     */
    pricing_model?: string;
    /**
     * Settlement currency
     */
    currency?: string;
    /**
     * Token alias for currency
     */
    token?: string;
    pi_smart_contract?: {
      address: string;
      network: "mainnet" | "testnet" | "sandbox";
      escrow_enabled?: boolean;
      abi_url?: string;
    };
    pricing?: {
      model?: "pay_per_call" | "subscription" | "freemium" | "tiered";
      cost_per_call?: {
        amount?: number;
        currency?: string;
      };
      subscription?: {
        monthly_fee?: {
          amount?: number;
          currency?: string;
        };
        included_calls?: number;
        additional_call_cost?: {
          amount?: number;
          currency?: string;
        };
      };
      tiered_pricing?: {
        min_calls?: number;
        max_calls?: number;
        cost_per_call?: {
          amount?: number;
          currency?: string;
        };
      }[];
    };
    [k: string]: unknown | undefined;
  };
  /**
   * Pi Network specific configuration and SDK integration
   */
  pi_network?: {
    app_id: string;
    environment: "sandbox" | "production";
    sdk_version?: string;
    payment_provider?: string;
    kyc_required?: boolean;
  };
  /**
   * Agent Bill of Materials (ABOM) — AI-SBOM compatible supply chain transparency
   */
  abom?: {
    /**
     * SHA-256 hash or short hash of the full ABOM for supply chain verification
     */
    integrity_hash?: string;
    spec_version?: string;
    /**
     * SBOM format (e.g. CycloneDX, A-BOM)
     */
    bom_format?: string;
    /**
     * Assessed risk level of the agent's dependency stack
     */
    risk_level?: "low" | "medium" | "high";
    generated?: ISODateTime;
    /**
     * Tool or system that generated this ABOM
     */
    generated_by?: string;
    timestamp?: ISODateTime;
    /**
     * High-level agent capability labels
     */
    capabilities?: string[];
    /**
     * Flat list of dependency identifiers
     */
    dependencies?: string[];
    /**
     * Underlying model metadata
     */
    model?: {
      provider?: string;
      name?: string;
      version?: string;
    };
    /**
     * Governance and license metadata
     */
    governance?: {
      license?: string;
      [k: string]: unknown | undefined;
    };
    tools?: {
      name?: string;
      version?: string;
    }[];
    /**
     * Supply chain components (models, datasets, libraries, tools)
     */
    constituents?: {
      name: string;
      version: string;
      type?: "model" | "dataset" | "library" | "tool" | "plugin" | "agent" | "runtime";
      /**
       * Package URL (purl) for this component — recommended but not required
       */
      purl?: string;
      hash?: string;
      integrity_hash?: string;
      license?: string;
      supplier?: string;
      trust_tier?: "verified" | "community" | "unverified" | "revoked";
      security_status?: "clean" | "vulnerable" | "revoked" | "unknown";
      source_registry?: string;
    }[];
    attestations?: {
      type?: string;
      value?: string;
      signer?: string;
    }[];
    [k: string]: unknown | undefined;
  };
  /**
   * Live Voice Models integration for human-like conversational experiences
   */
  live_voice?: {
    enabled: boolean;
    provider: "openai-realtime" | "hume" | "elevenlabs" | "generic";
    voice_id?: string;
    latency_mode?: "ultra_low" | "standard" | "high_quality";
  };
  /**
   * Agent resource requirements for deployment and execution
   */
  requirements?: {
    hardware?: {
      cpu_cores?: number;
      memory_mb?: number;
      storage_mb?: number;
      gpu_required?: boolean;
      gpu_memory_mb?: number;
    };
    software?: {
      runtime?: string;
      dependencies?: string[];
      python_version?: string;
      node_version?: string;
    };
    network?: {
      internet_access?: boolean;
      bandwidth_mbps?: number;
      allowed_domains?: string[];
    };
    vla?: {
      adapter: "openpi" | "π0.7" | "generic";
      vision?: {
        [k: string]: unknown | undefined;
      };
      language?: {
        [k: string]: unknown | undefined;
      };
      action?: {
        [k: string]: unknown | undefined;
      };
    };
  };
  meta_arbiter?: MetaArbiterConfig;
}
/**
 * Public key material for cryptographic verification
 *
 * This interface was referenced by `AIXFormat`'s JSON-Schema
 * via the `definition` "PublicKey".
 */
export interface PublicKey {
  /**
   * Cryptographic algorithm used to generate the key pair
   */
  algorithm: "Ed25519" | "secp256k1";
  /**
   * Base64url-encoded public key bytes
   */
  value: string;
  encoding?: "base64url" | "hex";
}
/**
 * Cryptographic signature over the canonical payload hash
 *
 * This interface was referenced by `AIXFormat`'s JSON-Schema
 * via the `definition` "Signature".
 */
export interface Signature {
  /**
   * Algorithm used to produce the signature
   */
  algorithm: "Ed25519" | "secp256k1";
  /**
   * Base64url-encoded signature bytes
   */
  value: string;
  /**
   * JSON canonicalization scheme used before signing
   */
  canonicalization?: "JCS" | "RFC8785";
}
/**
 * Optional Meta Arbiter runtime configuration — wires into the agent's orchestration layer
 */
export interface MetaArbiterConfig {
  /**
   * Minimum score (0-1) required to activate a subsystem
   */
  activation_threshold?: number;
  /**
   * Maximum number of subsystems running simultaneously
   */
  concurrent_systems_limit?: number;
  /**
   * Target maximum response time in seconds
   */
  response_time_target_sec?: number;
  /**
   * Maximum fraction of resources allocated to active systems
   */
  resource_allocation_ratio?: number;
  /**
   * Enable cognitive growth milestone tracking (GrowthMonitor)
   */
  growth_milestones_enabled?: boolean;
  /**
   * Default inter-system coordination strategy
   */
  coordination_strategy?: "sequential" | "parallel" | "hierarchical" | "collaborative" | "competitive";
  /**
   * Weighted criteria for subsystem activation decisions (weights should sum to 1.0)
   */
  decision_criteria?: {
    urgency?: number;
    complexity?: number;
    resource_availability?: number;
    user_preference?: number;
    system_capability?: number;
  };
  /**
   * SystemMonitor alert thresholds (mirrors SystemMonitor.alert_thresholds)
   */
  alert_thresholds?: {
    response_time_sec?: number;
    accuracy?: number;
    error_rate?: number;
    resource_usage?: number;
  };
  /**
   * Target cognitive growth milestone level (GrowthMonitor)
   */
  growth_milestone_level?: "beginner" | "intermediate" | "advanced" | "expert";
}
/**
 * Meta Arbiter — 'العقل المدبر' — orchestration config for the agent's internal subsystem controller. Controls activation thresholds, coordination strategy, and growth monitoring.
 *
 * This interface was referenced by `AIXFormat`'s JSON-Schema
 * via the `definition` "MetaArbiterConfig".
 */
export interface MetaArbiterConfig1 {
  /**
   * Minimum score (0-1) required to activate a subsystem
   */
  activation_threshold?: number;
  /**
   * Maximum number of subsystems running simultaneously
   */
  concurrent_systems_limit?: number;
  /**
   * Target maximum response time in seconds
   */
  response_time_target_sec?: number;
  /**
   * Maximum fraction of resources allocated to active systems
   */
  resource_allocation_ratio?: number;
  /**
   * Enable cognitive growth milestone tracking (GrowthMonitor)
   */
  growth_milestones_enabled?: boolean;
  /**
   * Default inter-system coordination strategy
   */
  coordination_strategy?: "sequential" | "parallel" | "hierarchical" | "collaborative" | "competitive";
  /**
   * Weighted criteria for subsystem activation decisions (weights should sum to 1.0)
   */
  decision_criteria?: {
    urgency?: number;
    complexity?: number;
    resource_availability?: number;
    user_preference?: number;
    system_capability?: number;
  };
  /**
   * SystemMonitor alert thresholds (mirrors SystemMonitor.alert_thresholds)
   */
  alert_thresholds?: {
    response_time_sec?: number;
    accuracy?: number;
    error_rate?: number;
    resource_usage?: number;
  };
  /**
   * Target cognitive growth milestone level (GrowthMonitor)
   */
  growth_milestone_level?: "beginner" | "intermediate" | "advanced" | "expert";
}
