#!/usr/bin/env tsx
/**
 * Codegen — regenerates `src/types.gen.ts` from `schemas/aix.schema.json`.
 *
 * Run locally:
 *   pnpm --filter @axiom/schema codegen
 *
 * CI ratchet (.github/workflows/axiom-schema-codegen.yml) runs the
 * same command and fails the build if the regenerated output differs
 * from the committed `src/types.gen.ts`. That guarantees the schema
 * and the generated TypeScript mirror never drift.
 *
 * Rich Axiom-specific types and runtime guards live in `src/types.ts`,
 * which is hand-authored. That file is the default public export of
 * the package; the codegen output is exposed at
 * `@axiom/schema/generated` for callers that want the raw mirror.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile, type JSONSchema } from 'json-schema-to-typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const schemaPath = resolve(pkgRoot, 'schemas/aix.schema.json');
const outPath = resolve(pkgRoot, 'src/types.gen.ts');

const schema = JSON.parse(readFileSync(schemaPath, 'utf-8')) as JSONSchema;

const banner = `/**
 * AUTOGENERATED — DO NOT EDIT BY HAND.
 *
 * Regenerate via: pnpm --filter @axiom/schema codegen
 * Source of truth: schemas/aix.schema.json
 *
 * Rich Axiom-specific types and runtime guards live in ./types.ts,
 * which is the default public export of @axiom/schema. The shapes
 * below are the raw mirror of the JSON Schema and are exposed under
 * @axiom/schema/generated for callers that want them.
 */
/* eslint-disable */`;

const ts = await compile(schema, 'AIXManifest', {
  bannerComment: banner,
  declareExternallyReferenced: true,
  enableConstEnums: false,
  unreachableDefinitions: true,
  strictIndexSignatures: true,
  style: {
    semi: true,
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 100,
  },
});

writeFileSync(outPath, ts);
console.log(`✓ Wrote ${outPath}`);
